# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 809639a0981a31685cd35c42326aae1b0bfe1805ce66056abc768f3d482081daa3c33ce514570cc627c82c42b8e6f6f853ccebe2df92c256a99c2c4ef518cf7b

test:
  secret_key_base: 8b73bcf5ed3cc59841feb9b98eb58bd13bcc8eff5e2a04b7dc3310881da4d55cf1c3f7f608cf6793ace84ed2c4045c653e4b102e7ef7d0aef03bebaf9f056e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
